# Generated by Django 4.0.6 on 2022-09-03 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Good_Benefits', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Img', models.ImageField(blank=True, upload_to='Img/')),
            ],
        ),
    ]
