# Generated by Django 4.0.6 on 2022-09-03 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Good_Benefits', '0002_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='Img',
            field=models.TextField(),
        ),
    ]
