# Generated by Django 4.0.6 on 2022-09-03 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Good_Benefits', '0003_alter_image_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=65, verbose_name='사용자명')),
                ('password', models.CharField(max_length=64, verbose_name='비밀번호')),
            ],
        ),
        migrations.RemoveField(
            model_name='image',
            name='Img',
        ),
        migrations.AddField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, upload_to='themeImages/'),
        ),
        migrations.AddField(
            model_name='image',
            name='title',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
